name: code-server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: pwd
      run: pwd
    - name: ls
      run: ls
    - name: install
      run: curl -fsSL https://code-server.dev/install.sh | sh
    - name: run
      run: code-server --link .
