name: code-server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install
      run: sudo npm i -g code-server
    - name: run
      run: code-server --link
